name: Run Automation on Production Deployment

on:
  repository_dispatch:
    types: [production-deployment]
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Automation Scripts
        run: npm test
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Send Slack Notification
        if: always()
        run: |
          curl -X POST -H "Content-type: application/json" \
          --data "{\"text\":\"✅ Automation Test Completed!\nReport: https://github.com/VijayaRaghavan21/QA_Neodove_Automation_Script/actions/runs/${{ github.run_id }}\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
